### ISSUE TITLE
Add support for Base64 encoding of resources

### ISSUE THREAD

**Issue by patrick-steele-idem** [lasso-js/lasso-less#6]
Example:

Input Less file:

```css
.data-image {
  background-image: url(./foo.png?base64);
}
```

Output CSS:

```
.data-image {
  background-image: url(data:image/png;base64,...);
}
```
